version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=2345
      - POSTGRES_USER=dev
      - POSTGRES_DB=api-historic-events

volumes:
  pgdata: